
spring:
  profiles:
    active: http
  application:
    name: feili-sap-bridge
  http:
    encoding:
      charset: UTF-8

jest:
  uris:
    - http://localhost:9200
  username: dev
  password: dev123

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

